spring.application.name=spring-caffine-impl
spring.datasource.url=jdbc:postgresql://localhost:5432/spring_caffine_impl
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.cache.type=caffeine
spring.cache.cache-names=books
spring.cache.caffeine.spec=maximumSize=500,expireAfterAccess=10m
app.gcs.bucket-name=
